### CREATE five documents.
POST http://localhost:3000/items HTTP/1.1
content-type: application/json

{
    "name": "American Cheese",
    "brand": "Kraft",
    "purchaseDate": "2023-12-18",
    "expireDate": "2024-04-23",
    "price": 12.99,
    "compartment": "Fridge",
    "amountOf": 3
}


### CREATE 2
POST http://localhost:8000/pantry-items HTTP/1.1
content-type: application/json

{
    "name": "Peanut Butter",
    "brand": "Jif",
    "purchaseDate": "2023-12-18",
    "expireDate": "2025-01-23",
    "price": 3.99,
    "compartment": "Pantry",
    "amountOf": 1
}

### CREATE 3
POST http://localhost:3000/items HTTP/1.1
content-type: application/json

{
    "name": "Chicken Breast",
    "brand": "",
    "purchaseDate": "2023-12-18",
    "expireDate": "2024-01-23",
    "price": 11.99,
    "compartment": "Freezer",
    "amountOf": 2
}

### CREATE 4
POST http://localhost:3000/items HTTP/1.1
content-type: application/json

{
    "name": "Whole Milk",
    "brand": "Horizon Organic",
    "purchaseDate": "2023-12-18",
    "expireDate": "2024-02-23",
    "price": 4.89,
    "compartment": "Fridge",
    "amountOf": 1
}

### CREATE 5
POST http://localhost:3000/items HTTP/1.1
content-type: application/json

{
    "name": "Salt",
    "brand": "Morton Salt",
    "purchaseDate": "2023-12-18",
    "expireDate": "",
    "price": 1.99,
    "compartment": "Pantry",
    "amountOf": 1
}

### RETRIEVE all documents.
GET http://localhost:3000/items HTTP/1.1


### RETRIEVE a document by its ID.
### Replace the following ID with one that exists in the collection.
GET http://localhost:3000/items/6580ce42c2c2674034427040 HTTP/1.1


### UPDATE one document by ID.
### Replace the ID in the following request with one that exists
### and update the year:
PUT http://localhost:3000/items/6580ce42c2c2674034427040 HTTP/1.1
content-type: application/json

{
    "name": "American Cheese",
    "brand": "Kraft",
    "purchaseDate": "2023-12-18",
    "expireDate": "2024-04-23",
    "price": 10.99,
    "compartment": "Fridge",
    "amountOf": 5
}

### DELETE by ID (responds with nothing if successful):
DELETE http://localhost:3000/items/6580ccabc2c2674034427038 HTTP/1.1



### RETRIEVE all documents (responds with 4 or the original 5):
GET http://localhost:3000/items HTTP/1.1

